config/routes.rb
Rails.application.routes.draw do
  
  resources :users
  resources :sessions

  root 'jobs#index'
  
  get 'home' => 'static_pages#home'
  
  get 'register' => 'users#new'
  
  get 'login' => 'sessions#new'
  
  post 'login' => 'sessions#create'
  
  delete 'logout' => 'sessions#destroy'

end

app/models/job.rb
class Job
  include Her::Model
  collection_path "hiring.php?" 
  
  def self.search(q = ' ', latitude = '37.73132', longitude = '-121.90968')
     self.create(:q => q, :latitude => latitude, :longitude => longitude)
  end
  
end 

app/models/login.rb
class Login
  include Her::Model
  collection_path "login.php?"
  
  attributes  :email, :password
  validates :password, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, 
                    format: { with: VALID_EMAIL_REGEX }
  
end

app/models/user.rb
class User 
  include Her::Model
  collection_path "register.php?"
  before_save :downcase_email
  
  attributes :first, :last, :location, :email, :type, :password
  
  validates :first, presence: true, length: { maximum: 25 }
  validates :last, presence: true, length: { maximum: 25 }
  validates :location, presence: true, length: { maximum: 100 }
  validates :password, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, 
                    format: { with: VALID_EMAIL_REGEX }

  
  
  private 
  
    #Converts email to all lower-case.
    def downcase_email
      self.email = email.downcase
    end 
  
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  def index
    @search = params[:search]
    if params[:search].blank?
      @jobs = Job.search() #would use ipgecode in production, default = San Ramon, CA
      @markers = Array.new 
      for i in 0..@jobs.response[:offers].length-1 do 
        @markers[i] = {lng: @jobs.response[:offers][i][:offer][:longitude],
                                           lat: @jobs.response[:offers][i][:offer][:latitude], infowindow: "#{i+1}. #{@jobs.response[:offers][i][:offer][:title]}"} 
      end 
      respond_to do |format|
          format.html
          format.js
      end 
    else 
      @jobs = Job.search(@search) #would use ipgeocode in production, default = San Ramon, CA
      @markers = Array.new 
      for i in 0..@jobs.response[:offers].length-1 do 
        @markers[i] = {lng: @jobs.response[:offers][i][:offer][:longitude],
                                           lat: @jobs.response[:offers][i][:offer][:latitude], infowindow: "#{i+1}. #{@jobs.response[:offers][i][:offer][:title]}"} 
      end
      respond_to do |format|
          format.html
          format.js
      end  
    end
  end 
  
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new 
  end
  
  def create
    log_in(params[:email], params[:password])
  end 
  
  def destroy 
    log_out if logged_in?
    redirect_to root_url 
  end
  
  
  private 
 
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home 
  end 
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new 
    @user = User.new(email: nil, first: nil, last: nil,
                                location: nil, type: nil, password: nil) 
  end 
  
  def create
    @user = User.new(user_params)
    
    if @user.valid? && @user.save && @user.response[:success] == 1
      log_in(@user.email, @user.password)
      flash[:info] = "Please check your email to activate your account."
    else  
     render 'new'
    end
      
  end 
  
  def show
    
  end
  
  def update
  end 
  
  def destroy 
  end 
  
  private 
  
  def user_params
    params.require(:user).permit(:first, :last, :location, 
                                :type, :email, :password)                             
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def full_title(page_title = '')
    base_title = "Ziglee"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
  
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user. 
  
  #Logs out the user. 
  def log_out
    session.delete(:id)
    session.delete(:token)
    session.delete(:type)
    @current_user = nil 
  end 
  
  def logged_in?
    !current_user.nil?
  end
  
   
  
  private
  
  def log_in(email, password)
    user = Login.new(email: email, password: password)
    if user.valid? && user.save && user.response[:success] == 1
      session[:id] = user.response[:userCredentials][:id]
      session[:token] = user.response[:userCredentials][:token]
      session[:type] = user.response[:userCredentials][:indicator]
      session[:email] = user.email
      redirect_to root_url
    else
      flash.now[:alert] = "Invalid email or password"
      render "sessions/new"
    end    
  end 
  
  def current_user 
    @current_user ||= {:id => session[:id], :token => session[:token], :type => session[:type], :email => session[:email]} if session[:id]
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/jobs/_map.html.erb
<div id="map" style='width: 100%; height: 100%;'></div>

	<script type="text/javascript" charset="utf-8">
	var myStyle = [{"featureType":"landscape","stylers":[{"saturation":-100},{"lightness":65},{"visibility":"on"}]},{"featureType":"poi","stylers":[{"saturation":-100},{"lightness":51},{"visibility":"simplified"}]},{"featureType":"road.highway","stylers":[{"saturation":-100},{"visibility":"simplified"}]},{"featureType":"road.arterial","stylers":[{"saturation":-100},{"lightness":30},{"visibility":"on"}]},{"featureType":"road.local","stylers":[{"saturation":-100},{"lightness":40},{"visibility":"on"}]},{"featureType":"transit","stylers":[{"saturation":-100},{"visibility":"simplified"}]},{"featureType":"administrative.province","stylers":[{"visibility":"off"}]},{"featureType":"water","elementType":"labels","stylers":[{"visibility":"on"},{"lightness":-25},{"saturation":-100}]},{"featureType":"water","elementType":"geometry","stylers":[{"hue":"#ffff00"},{"lightness":-25},{"saturation":-97}]}];
	</script>

	<script type="text/javascript">
	handler = Gmaps.build('Google', { markers: { maxRandomDistance: false } });
	handler.buildMap({ provider: {
		styles: myStyle,
	
	
	}, internal: {id: 'map'}}, function(){
	  markers = handler.addMarkers(<%= raw @markers.to_json %>);
	  handler.bounds.extendWith(markers);
	  handler.fitMapToBounds();
	});
	</script>

app/views/jobs/_results.html.erb
	<% for i in 0..@jobs.response[:offers].length-1 do %>
		<a class="result" href="<%=@jobs.response[:offers][i][:offer][:pic]%>">
			<div class="row">
			
				<div class="small-4 medium-2 large-3 columns">
					<img id="profile" src="<%=@jobs.response[:offers][i][:offer][:pic]%>" alt="Profile Picture">
				</div>
			
				<div class="small-8 medium-10 large-9 columns">
					<h5 class="text-left"><%= @jobs.response[:offers][i][:offer][:title].split.map(&:capitalize).join(' ')%></h5>
					<h6 class-"text-left"><%= @jobs.response[:offers][i][:offer][:name]%> | <%= @jobs.response[:offers][i][:offer][:category].capitalize!%></h6>
					<p id="description"><%= @jobs.response[:offers][i][:offer][:description]%></p>
			    </div>
		
			</div>
			<hr>
		</a>
	<%end%>

app/views/jobs/_scripts.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

app/views/jobs/index.html.erb
<div class="row collapse fullWidth" style="height:100%;">
<%= render "scripts" %>

 <div id="maps" class="large-7 large-push-5 columns" style="height:100%;">

   <%= render "map" %>

 </div>
  
 <div class="large-5 large-pull-7 columns" style="height:100%;">
	
	<%= form_tag '/', :method => :get, :remote => true do %>
     <div id="search-box" class="row collapse">
		<div class="small-10 columns">
	     	<%= text_field_tag "search", nil, placeholder: "Search Jobs" %>
		</div>
		<div class="small-2 columns">
			<%= button_tag(type: "submit", class: "button postfix") do %>
			   <i class="fi-magnifying-glass"></i>
			<% end %>
		</div>
     </div>

	<% end %>
	
 <div id="results" class="row" style="height:100%; overflow-y:auto;">
	 	
	<%= render "results" %>
	
 </div>	

 </div>
 
</div>
 

app/views/jobs/index.js.erb
$('#results').html("<%= escape_javascript(render 'results' ) %>");

$('#maps').html("<%= escape_javascript(render 'map' ) %>");

app/views/layouts/_header.html.erb
<header>
  <div class="row fullWidth">
	<nav class="top-bar" data-topbar data-no-turbolink role="navigation" data-options="is_hover: true">
	  <ul class="title-area"> 
	    <li class="name"><h1><%= link_to "Ziglee", root_path %></h1></li>
	     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
	    <li class="toggle-topbar menu-icon"><a href="javascript:;"><span>Menu</span></a></li>
	  </ul>

	  <section class="top-bar-section">
	    <!-- Right Nav Section -->
	    <ul class="right">
		  <%if logged_in? %>
		  <li class="has-dropdown">
		          <a href="#"><%= current_user[:email] %></a>
		          <ul class="dropdown">
		            <li><a href="#">Profile</a></li>
					<li><a href="#">Messages</a></li>
		          </ul>
		  </li>
		  <li class="divider"></li>
		  <li><%= link_to "Log Out", logout_path, method: "delete" %></li>
		  <%else%>
	      <li><%= link_to "Log In", login_path %></li>
		  <li class="divider"></li>
		  <li><%= link_to "Register", register_path %></li>
		  <%end%>
	    </ul>
	  </section>
	</nav>
  </div> 
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.2/html5shiv.js"></script>
  <script src="//s3.amazonaws.com/nwapi/nwmatcher/nwmatcher-1.2.5-min.js"></script>
  <script src="//html5base.googlecode.com/svn-history/r38/trunk/js/selectivizr-1.0.3b.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.1.0/respond.min.js"></script>
<![endif]-->
            

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= full_title(yield(:title)) %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
	<%= render 'layouts/shim' %>
  </head>

  <body>  
	<%= render 'layouts/header' %>
	
    <%= display_flash_messages %>
	
	<div id="main-content" class="row fullWidth" style="height:100%;">
	  
    <%= yield %>
	
    </div>
	

  </body>
</html>

app/views/static_pages/home.html.erb
<div class="large-12 columns home-page" style="height:800px;">
	

</div>

app/views/users/new.html.erb
<% provide(:title, 'Register')%>

<h3 class="text-center">Register</h3>

<div class="large-6 large-offset-3 columns">
	
	<%= form_for(@user) do |f| %>
	
	      <%= f.text_field :first, label: "First Name", :placeholder => "John"%>
		  
		  <%= f.text_field :last, label: "Last Name", :placeholder => "Doe"%>
		  
		  <%= f.text_field :location,label: "Location", :placeholder => "San Francisco, CA"%>
		  
		  <%= f.select(:type, [['Worker', 0], ['Employer', 1]]) %>

	      <%= f.text_field :email, :placeholder => "john@doe.com"%>

	      <%= f.password_field :password, :placeholder => "Password"%>
		  
          <div class="text-center">
	      <%= f.submit "Create my account"%>
	      </div>

	 <% end %>

</div>
	